"""add_qty_used_to_job_parts

Revision ID: 0131a359526c
Revises: 34977136a37b
Create Date: 2026-06-11 11:47:02.074932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0131a359526c'
down_revision: Union[str, None] = '34977136a37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_parts', sa.Column('qty_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_parts', 'qty_used')
    # ### end Alembic commands ###
