"""add_ai_fields_to_jobs

Revision ID: 34977136a37b
Revises: 440181d7a967
Create Date: 2026-06-11 11:18:13.507285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34977136a37b'
down_revision: Union[str, None] = '440181d7a967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ai_service_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('ai_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ai_explanation')
    op.drop_column('jobs', 'ai_confidence')
    op.drop_column('jobs', 'ai_service_type')
    # ### end Alembic commands ###
