"""add_low_stock_threshold_to_parts

Revision ID: b53862372731
Revises: 34977136a37b
Create Date: 2026-06-11 11:33:56.397073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53862372731'
down_revision: Union[str, None] = '34977136a37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('low_stock_threshold', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'low_stock_threshold')
    # ### end Alembic commands ###
